version: "3.8"

services:
  app:
    build:
      context: ./app
    container_name: node_app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm run start"
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=node_db
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_db
    volumes:
      - ./app/mysql-init-scripts:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
